/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RLWEModule"
 * 	found in "./rlweModule.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#include "RLWEClientKeyExchange.h"

static asn_TYPE_member_t asn_MBR_RLWEClientKeyExchange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLWEClientKeyExchange, oid),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"oid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLWEClientKeyExchange, b),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"b"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLWEClientKeyExchange, c),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"c"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLWEClientKeyExchange, sig),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sig"
		},
};
static const ber_tlv_tag_t asn_DEF_RLWEClientKeyExchange_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RLWEClientKeyExchange_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 2 }, /* b */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, -1, 1 }, /* c */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, -2, 0 }, /* sig */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* oid */
};
static asn_SEQUENCE_specifics_t asn_SPC_RLWEClientKeyExchange_specs_1 = {
	sizeof(struct RLWEClientKeyExchange),
	offsetof(struct RLWEClientKeyExchange, _asn_ctx),
	asn_MAP_RLWEClientKeyExchange_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RLWEClientKeyExchange = {
	"RLWEClientKeyExchange",
	"RLWEClientKeyExchange",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RLWEClientKeyExchange_tags_1,
	sizeof(asn_DEF_RLWEClientKeyExchange_tags_1)
		/sizeof(asn_DEF_RLWEClientKeyExchange_tags_1[0]), /* 1 */
	asn_DEF_RLWEClientKeyExchange_tags_1,	/* Same as above */
	sizeof(asn_DEF_RLWEClientKeyExchange_tags_1)
		/sizeof(asn_DEF_RLWEClientKeyExchange_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RLWEClientKeyExchange_1,
	4,	/* Elements count */
	&asn_SPC_RLWEClientKeyExchange_specs_1	/* Additional specs */
};

