/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RLWEModule"
 * 	found in "./rlweModule.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_RLWEServerKeyExchange_H_
#define	_RLWEServerKeyExchange_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OBJECT_IDENTIFIER.h"
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RLWEServerKeyExchange */
typedef struct RLWEServerKeyExchange {
	OBJECT_IDENTIFIER_t	 oid;
	OCTET_STRING_t	 kem;
	OCTET_STRING_t	 sig;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLWEServerKeyExchange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLWEServerKeyExchange;

#ifdef __cplusplus
}
#endif

#endif	/* _RLWEServerKeyExchange_H_ */
#include "asn_internal.h"
