/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RLWEModule"
 * 	found in "./rlweModule.asn1"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_RLWECert_H_
#define	_RLWECert_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RLWEAlgorithm.h"
#include "BIT_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RLWECert */
typedef struct RLWECert {
	RLWEAlgorithm_t	 alg;
	BIT_STRING_t	 data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLWECert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RLWECert;

#ifdef __cplusplus
}
#endif

#endif	/* _RLWECert_H_ */
#include "asn_internal.h"
